# configs/default.yaml
# ------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------
data:
  # Root folder that holds dev_data/ and eval_data/ (download script creates it)
  root: data/dcase2025t2

  # Where pre-cached log-mel tensors will be stored by preprocess.py
  # (train_knn.py / infer.py look here first; falls back to WAVs if missing)
  melspec_dir: ${data.root}/melspec

  # Use the 10 “target-domain” normals from eval_data/train when building
  # the memory bank?  (true = include them, false = ignore)
  use_eval_normals: true


train:
  batch_size: 16       # same value you put in dataloader.batch_size
  num_workers: 2       # same as dataloader.num_workers

# ------------------------------------------------------------------
# Model
# ------------------------------------------------------------------
model:
  embedding: HUBERT_BASE          # built-in pipeline available in torchaudio 2.3
  pooling: mean                   # time-avg over frame-level embeddings
  normalize: true                 # L2-norm each embedding before k-NN

detector:
  k: 3                            # k-nearest neighbours
  distance: cosine

# ------------------------------------------------------------------
# Training / inference misc
# ------------------------------------------------------------------
dataloader:
  batch_size: 16
  num_workers: 2                  # Codespaces CPU warning suggests 2

device: auto                      # "auto" ⇒ CUDA if available, else CPU

logging:
  level: info
  csv_out_dir: results/csv        # infer.py writes DCASE-style CSVs here
  bank_out:   results/memory_bank # train_knn.py writes .pt and manifest.json
